services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_started
      mongo:
        condition: service_started
      mongo-express:
        condition: service_started
      neo4j_db:
        condition: service_started
        
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  neo4j_db:
    image: neo4j:5.26.0
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/examplXms1024m
    ports:
      - 7474:7474
    