services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres_db:
        condition: service_healthy
        
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080